export enum RouteNames {
  START = '/',
  LOGIN = '/login',
  REGISTRATION = '/registration',
  ERROR = '/error',
  FORUM = '/forum',
  GAME = '/game',
  FORUM_EVENTS = '/forum/:id',
  TOPIC = 'forum/topics/:forumId/:topicId',
  FORUM_ANSWERS = 'forum/answers',
  LEADERS = '/leaders',
  PROGRESS = '/progress',
  PROFILE = '/profile',
  NOMATCH = '*',
}
