export enum RouteNames {
  START = '/',
  LOGIN = '/login',
  REGISTRATION = '/registration',
  ERROR = '/error',
  FORUM = '/forum',
  FORUM_TOPICS = 'forum/topics',
  FORUM_ANSWERS = 'forum/answers',
  FORUM_CREATE = 'forum/create',
  GAME = '/game',
  FORUM_EVENTS = '/forum/:id',
  LEADERS = '/leaders',
  PROGRESS = '/progress',
  PROFILE = '/profile',
  NOMATCH = '*',
}
